mredis:
  image: redis
  hostname: redis
  domainname: localdomain

scmmetrics:
  build: scmmetrics
  hostname: scmmetrics
  domainname: localdomain
  links:
    - mredis:redis
  environment:
    - TERM=xterm
    - CONFIG=sdh.metrics.scm.config.ProductionConfig
    - AGORA_HOST=
    - AGORA_PORT=
    - BROKER_HOST=
    - METRICS_HOST=
    - METRICS_PORT=
    - BROKER_PORT=
    - API_PORT=5003
    - DB_DB=6
    - DB_HOST=redis
  ports:
    - 5003:5003
  mem_limit: 1000000000

cimetrics:
  build: cimetrics
  hostname: cimetrics
  domainname: localdomain
  links:
    - mredis:redis
  environment:
    - TERM=xterm
    - CONFIG=sdh.metrics.ci.config.ProductionConfig
    - AGORA_HOST=
    - AGORA_PORT=
    - BROKER_HOST=
    - METRICS_HOST=
    - METRICS_PORT=
    - BROKER_PORT=
    - API_PORT=5005
    - DB_DB=5
    - DB_HOST=redis
  ports:
    - 5005:5005
  mem_limit: 1000000000

orgmetrics:
  build: orgmetrics
  hostname: orgmetrics
  domainname: localdomain
  links:
    - mredis:redis
  environment:
    - TERM=xterm
    - CONFIG=sdh.metrics.org.config.ProductionConfig
    - AGORA_HOST=
    - AGORA_PORT=
    - BROKER_HOST=
    - METRICS_HOST=
    - METRICS_PORT=
    - BROKER_PORT=
    - API_PORT=5004
    - DB_DB=7
    - DB_HOST=redis
  ports:
    - 5004:5004
  mem_limit: 1000000000

qmetrics:
  build: qmetrics
  hostname: qmetrics
  domainname: localdomain
  links:
    - mredis:redis
  environment:
    - TERM=xterm
    - CONFIG=sdh.metrics.qualitative.config.ProductionConfig
    - AGORA_HOST=
    - AGORA_PORT=
    - BROKER_HOST=
    - METRICS_HOST=
    - METRICS_PORT=
    - BROKER_PORT=
    - API_PORT=5006
    - DB_DB=8
    - DB_HOST=redis
  ports:
    - 5006:5006
  mem_limit: 1000000000

nginx:
  build: nginx
  hostname: nginx
  domainname: localdomain
  links:
    - scmmetrics:scmmetrics
    - cimetrics:cimetrics
    - orgmetrics:orgmetrics
    - qmetrics:qmetrics
  ports:
    - "9004:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
