#!/usr/bin/env python

import requests
import time
import os

agora_host = os.environ.get('AGORA_HOST', '') + ':' + str(os.environ.get('AGORA_PORT', ''))
metric_host = os.environ.get('METRICS_HOST', 'http://127.0.0.1') + ':' + str(os.environ.get('METRICS_PORT', ''))
 
def seed(t, u):
    r = requests.post('http://' + agora_host + '/seeds', json={'type': t, 'uri': u})
    print 'Load {} seed: {}'.format(t, r.status_code)

con = False
cou = 0
while not con:
    try:
        seed('metrics:MetricService', 'http://' + metric_host + '/scm/api')
        seed('views:ViewService', 'http://' + metric_host + '/scm/api')
        con = True
    except Exception:
        cou += 1
        if cou > 5:
            break
        time.sleep(1)
